### Get Users
GET http://localhost:4004/project/Users

### Get User
GET http://localhost:4004/project/Users(8476b626-7001-4ea3-9dab-d2ce43ffb197)
CustomHeader: 123456


### Get Projects
GET http://localhost:4004/project/Projects


### Add User
POST http://localhost:4004/project/Users
Content-Type: application/json

{
    "name"  : "Jane Doe",
    "email" : "jane.doe@gmail.com",
    "phone": "555-555-5555",
    "gender": "Male",
    "password": "123456",
    "address_street": "8000 Avalon Blvd",
    "address_city": "Alpharetta",
    "address_state": "GA",
    "address_zip": "30004",
    "project_id": "7a68de55-7048-419d-8694-bf340bcccb2e"
}